# syntax=docker/dockerfile:1

ARG ADC_IMAGE=arbattest-adc:local
ARG NITRO_TPM_TOOLS_REF=a37ff598acf32e3c8c2c85d53bb8f4025b0a12d7

FROM rust:1.92-trixie AS nitro-tpm-tools

ARG NITRO_TPM_TOOLS_REF

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        git \
        libssl-dev \
        libtss2-dev \
        pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src

RUN git clone https://github.com/aws/NitroTPM-Tools.git \
    && cd NitroTPM-Tools \
    && git checkout "$NITRO_TPM_TOOLS_REF" \
    && cargo build --release -p nitro-tpm-attest

FROM ${ADC_IMAGE}

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        awscli \
        curl \
        libtss2-esys-3.0.2-0t64 \
        libtss2-mu-4.0.1-0t64 \
        libtss2-tctildr0t64 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=nitro-tpm-tools /src/NitroTPM-Tools/target/release/nitro-tpm-attest /usr/local/bin/nitro-tpm-attest
COPY service/attested/adc/exec-container-entrypoint.sh /usr/local/bin/exec-container-entrypoint

RUN chmod 755 /usr/local/bin/nitro-tpm-attest /usr/local/bin/exec-container-entrypoint

ENTRYPOINT ["/usr/local/bin/exec-container-entrypoint"]
